version: "3.8"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
  db:
    image: "postgres:13.1-alpine"
    restart: always
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
  dbadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8081:80"
